version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - phonebook-mysql
    ports:
      - "8080:8080"
    restart: always
